version: "3.6"
services:
  proxy:
    build: .
    ports:
      - 80:80
    external_links: 
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    external: 
      name: app-network